type Member @collection(name: "members") {
  username: String!
  initialRating: Int!
  currentRating: Int!
}

type Query {
  allMembers: [Member!]
}

type Mutation {
  addMember(
    username: String!
    initialRating: Int!
    currentRating: Int!
  ): Member @resolver(name: "addMember")
  updateMember(username: String!, rating: Int!): Member
    @resolver(name: "updateMember")
  fixMistake(spell: Int!): Member @resolver(name: "fixMistake")
}
